# Generated by Django 5.2.7 on 2025-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coursebundle',
            old_name='bundle_id',
            new_name='bundle',
        ),
        migrations.RenameField(
            model_name='coursebundle',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='bundle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
